# Generated by Django 3.2.23 on 2024-01-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('habitacion', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservacion',
        ),
    ]
